name: Build Latest

on:
  workflow_dispatch:

jobs:
  build:
    uses: kwitsch/ziggoimg/.github/workflows/build-version.yml@main
    with:
      zig_version: ${{ vars.LATEST_ZIG_VERSION }}
      docker_tag: "latest"
