name: Build Latest

on:
  workflow_dispatch:
  workflow_call:

permissions:
  security-events: write
  actions: read
  contents: read
  packages: write

jobs:
  build:
    name: Build Latest Image
    uses: kwitsch/ziggoimg/.github/workflows/build-version.yml@main
    with:
      zig_version: ${{ vars.LATEST_ZIG_VERSION }}
      docker_tag: "latest"

  scan:
    name: Scan Latest Image
    uses: kwitsch/ziggoimg/.github/workflows/scan-image.yml@main
    needs: build
    with:
      docker_tag: "latest"
