name: Build Latest

on:
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read
  packages: write

jobs:
  build:
    uses: kwitsch/ziggoimg/.github/workflows/build-version.yml@main
    with:
      zig_version: ${{ vars.LATEST_ZIG_VERSION }}
      docker_tag: "latest"
