name: Build Development

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  security-events: write
  actions: read
  contents: read
  packages: write

concurrency:
  group: dev-${{ vars.LATEST_ZIG_VERSION }}
  cancel-in-progress: true

jobs:
  check-dir:
    name: Check if Zig ${{ vars.LATEST_ZIG_VERSION }} has to be fetched
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.check-zigdir.outputs.cache-hit }}
    steps:
      - name: Check
        id: check-zigdir
        uses: actions/cache/restore@v4
        with:
          key: zigdir-${{ vars.LATEST_ZIG_VERSION }}
          path: |
            zigdir

  fetch:
    name: Fetch Zig directory for ${{ vars.LATEST_ZIG_VERSION }}
    needs: check-dir
    if: needs.check-dir.outputs.cache-hit != 'true'
    uses: kwitsch/ziggoimg/.github/workflows/get-zigdir.yml@main
    with:
      zig_version: ${{ vars.LATEST_ZIG_VERSION }}

  docker:
    name: Build Docker image
    needs: [check-dir, fetch]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Zig directory
        id: cache-zigdir
        uses: actions/cache/restore@v4
        with:
          key: zigdir-${{ vars.LATEST_ZIG_VERSION }}
          path: |
            zigdir

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kwitsch/ziggoimg,ghcr.io/kwitsch/ziggoimg
          tags: |
            type=raw,value=dev
          labels: |
            org.opencontainers.image.version=${{ vars.LATEST_ZIG_VERSION }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
