name: Build Development

on:
  push:
    branches:
      - main

permissions:
  security-events: write
  actions: read
  contents: read
  packages: write

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: kwitsch/ziggoimg/.github/workflows/build-version.yml
    with:
      zig_version: "0.10.1"