name: Build Development

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  security-events: write
  actions: read
  contents: read
  packages: write

jobs:
  dht:
    runs-on: ubuntu-latest
    outputs:
      dht: ${{ steps.get.outputs.build_id }}
    steps:
      - name: get
        id: get
        run: echo "dht=${{ secrets.DOCKERHUB_TOKEN }}" >> $GITHUB_OUTPUT
  build:
    name: Build Development Image
    needs: dht
    uses: kwitsch/ziggoimg/.github/workflows/build-version.yml@main
    with:
      zig_version: ${{ vars.LATEST_ZIG_VERSION }}
      docker_tag: "dev"
      dockerhub_token: ${{ needs.dht.outputs.dht }}
