name: Build Development

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read
  packages: write

jobs:
  build:
    uses: kwitsch/ziggoimg/.github/workflows/build-version.yml@main
    with:
      zig_version: "0.11.0"
      docker_tag: "dev"
