name: Get Zig Directory

on:
 workflow_call:
   inputs:
     zig_version:
       description: "Zig version"
       required: true
       type: string

concurrency: 
  group: get-zig-dir-${{ inputs.zig_version }}

jobs:
  docker:
    name: Get Zig directory for ${{ inputs.zig_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Cache Zig
        id: cache-zig
        uses: actions/cache@v4
        with:
          key: zig-${{ inputs.zig_version }}
          path: |
            zig.tar.xz
            zig.tar.xz.minisign
      
      - name: Get Zig
        if: steps.cache-zig.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl --location --request GET 'https://ziglang.org/download/${{ inputs.zig_version }}/zig-linux-x86_64-${{ inputs.zig_version }}.tar.xz' \
          --header 'User-Agent: Chrome/113.0.0.0' \
          --header 'Referer: https://ziglang.org/download/' \
          --header 'Sec-Ch-Ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
          --header 'Sec-Ch-Ua-Mobile: ?0' \
          --header 'Sec-Ch-Ua-Platform: "Linux"' \
          --header 'Sec-Fetch-Dest: document' \
          --header 'Sec-Fetch-Mode: navigate' \
          --header 'Sec-Fetch-Site: same-origin' \
          --header 'Sec-Fetch-User: ?1' \
          -o 'zig.tar.xz'

          curl --location --request GET 'https://ziglang.org/download/${{ inputs.zig_version }}/zig-linux-x86_64-${{ inputs.zig_version }}.tar.xz.minisig' \
          --header 'User-Agent: Chrome/113.0.0.0' \
          --header 'Referer: https://ziglang.org/download/' \
          --header 'Sec-Ch-Ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
          --header 'Sec-Ch-Ua-Mobile: ?0' \
          --header 'Sec-Ch-Ua-Platform: "Linux"' \
          --header 'Sec-Fetch-Dest: document' \
          --header 'Sec-Fetch-Mode: navigate' \
          --header 'Sec-Fetch-Site: same-origin' \
          --header 'Sec-Fetch-User: ?1' \
          -o 'zig.tar.xz.minisign'

          cat zig.tar.xz.minisign

      - name: Verify download
        if: steps.cache-zig.outputs.cache-hit != 'true'
        uses: thomasdesr/minisign-action@v1
        with:
          args: -Vm zig.tar.xz -x zig.tar.xz.minisign -P "RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U"

      - name: Cache Zig directory
        id: cache-zigdir
        uses: actions/cache@v4
        with:
          key: zigdir-${{ inputs.zig_version }}
          path: |
            zigdir

      - name: Extract Zig
        shell: bash
        run: |
          mkdir -p ./zigdir
          tar -Jxf zig.tar.xz -C "./zigdir" --strip-components=1

          rm -R ./zigdir/lib/libc/include/any-windows-any
          rm -R ./zigdir/lib/libc/include/aarch64-macos.12-none
          rm -R ./zigdir/lib/libc/include/aarch64-macos.13-none
          rm -R ./zigdir/lib/libc/include/any-macos-any
          rm -R ./zigdir/lib/libc/include/any-macos.12-any
          rm -R ./zigdir/lib/libc/include/any-macos.13-any
          rm -R ./zigdir/doc
