name: Scan Latest Image & Rebuild on security vulnerability

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  security-events: write
  actions: read
  contents: read
  packages: write

concurrency:
  group: latest-image-scan
  cancel-in-progress: true

jobs:
  image-scan:
    name: Image vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/kwitsch/ziggoimg:latest
          severity_threshold: MEDIUM
          dockerfile: ./Dockerfile

  build:
    name: Rebuild Latest Image
    uses: kwitsch/ziggoimg/.github/workflows/build-latest.yml@main
    needs: image-scan
    if: failure()
