name: Scan Latest Image & Rebuild on security vulnerability

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  security-events: write
  actions: read
  contents: read
  packages: write

concurrency:
  group: latest-image-scan
  cancel-in-progress: true

jobs:
  image-scan:
    name: Image vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/kwitsch/ziggoimg:latest
          severity_threshold: MEDIUM
          dockerfile: ./Dockerfile

  docker:
    name: Build Docker image
    needs: [image-scan]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kwitsch/ziggoimg,ghcr.io/kwitsch/ziggoimg
          tags: |
            type=semver,pattern={{version}},value=v${{ vars.LATEST_ZIG_VERSION }}
            type=semver,pattern={{major}},value=v${{ vars.LATEST_ZIG_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ vars.LATEST_ZIG_VERSION }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/kwitsch/ziggoimg:latest
          severity_threshold: MEDIUM
          dockerfile: ./Dockerfile
