name: Scan Latest Image & Rebuild on security vulnerability

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  security-events: write
  actions: read
  contents: read

concurrency:
  group: latest-image-scan
  cancel-in-progress: true

jobs:
  image-scan:
    name: Image vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/kwitsch/ziggoimg:latest
          severity_threshold: HIGH

  build:
    name: Rebuild Latest Image
    uses: kwitsch/ziggoimg/.github/workflows/build-latest.yml@main
    needs: image-scan
    if: failure()
