name: Scan Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  security-events: write
  actions: read
  contents: read

concurrency:
  group: latest-image-scan
  cancel-in-progress: true

jobs:
  scan:
    name: Scan Latest Image
    uses: kwitsch/ziggoimg/.github/workflows/scan-image.yml@main
    with:
      docker_tag: "latest"
